<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright © 2025-2026 Markus Spann, SpeedBankingDe

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.speedbanking</groupId>
    <artifactId>iban-commons-benchmarks</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>IBAN Commons Benchmarks</name>
    <description>JMH Microbenchmarks for comparing IBAN validation and object creation performance of popular Java libraries</description>
    <url>https://www.speedbanking.de/</url>
    <inceptionYear>2025</inceptionYear>

    <organization>
        <name>SpeedBankingDe</name>
        <url>${project.url}</url>
    </organization>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>${developer1Id}</id>
            <name>${developer1Name}</name>
            <email>${developer1Email}</email>
        </developer>
        <developer>
            <id>${developer2Id}</id>
            <name>${developer2Name}</name>
            <email>${developer2Email}</email>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:ssh//git@github.com/${project.organization.name}/${project.artifactId}.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/${project.organization.name}/${project.artifactId}.git</developerConnection>
        <url>https://github.com/${project.organization.name}/${project.artifactId}/tree/master</url>
        <tag></tag>
    </scm>

    <issueManagement>
        <system>Github</system>
        <url>${project.url}/issues</url>
    </issueManagement>

    <properties>
        <!-- require Java 11 for iban4j -->
        <javaVersion>11</javaVersion>

        <jmhMainClass>org.openjdk.jmh.Main</jmhMainClass>
        <dep.jmh.version>1.37</dep.jmh.version>

        <dep.iban-commons.version>1.8.3</dep.iban-commons.version>
        <dep.iban4j.version>3.2.12-RELEASE</dep.iban4j.version>
        <dep.apache-commons-validator.version>1.10.1</dep.apache-commons-validator.version>
        <dep.garvelink-iban.version>1.16.0</dep.garvelink-iban.version>

        <developer1Id>spannm</developer1Id>
        <developer1Name>Markus Spann</developer1Name>
        <developer1Email>spannm@outlook.de</developer1Email>

        <developer2Id>spannn</developer2Id>
        <developer2Name>Noah Spann</developer2Name>
        <developer2Email>spannn@outlook.de</developer2Email>

        <maven.compiler.release>${javaVersion}</maven.compiler.release>
        <maven.compiler.source>${javaVersion}</maven.compiler.source>
        <maven.compiler.target>${javaVersion}</maven.compiler.target>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss.SSS</maven.build.timestamp.format>

        <check.checkstyle.ruleset>src/test/resources/team/checkstyle-rules.xml</check.checkstyle.ruleset>
        <dep.checkstyle.version>13.3.0</dep.checkstyle.version>

        <!-- Plugin versions (alphabetically) -->
        <dep.plugin.antrun>3.2.0</dep.plugin.antrun>
        <dep.plugin.checkstyle.version>3.6.0</dep.plugin.checkstyle.version>
        <dep.plugin.compiler.version>3.15.0</dep.plugin.compiler.version>
        <dep.plugin.enforcer.version>3.6.2</dep.plugin.enforcer.version>
        <dep.plugin.jar.version>3.5.0</dep.plugin.jar.version>
        <dep.plugin.resources.version>3.5.0</dep.plugin.resources.version>
        <dep.plugin.shade.version>3.6.2</dep.plugin.shade.version>
        <dep.plugin.versions.version>2.21.0</dep.plugin.versions.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-core</artifactId>
            <version>${dep.jmh.version}</version>
        </dependency>

        <dependency>
            <groupId>de.speedbanking</groupId>
            <artifactId>iban-commons</artifactId>
            <version>${dep.iban-commons.version}</version>
        </dependency>

        <dependency>
            <groupId>org.iban4j</groupId>
            <artifactId>iban4j</artifactId>
            <version>${dep.iban4j.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>${dep.apache-commons-validator.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-beanutils</groupId>
                    <artifactId>commons-beanutils</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-digester</groupId>
                    <artifactId>commons-digester</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-collections</groupId>
                    <artifactId>commons-collections</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>nl.garvelink.oss</groupId>
            <artifactId>iban</artifactId>
            <version>${dep.garvelink-iban.version}</version>
        </dependency>

    </dependencies>

    <build>

        <defaultGoal>clean package</defaultGoal>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>run-benchmarks.*</include>
                </includes>
            </resource>
        </resources>

        <pluginManagement>

            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${dep.plugin.compiler.version}</version>
                    <configuration>
                        <debug>true</debug>
                        <debuglevel>lines,vars,source</debuglevel>
                        <showWarnings>true</showWarnings>
                        <showDeprecation>true</showDeprecation>
                        <compilerArgument>-Xlint:all,-options</compilerArgument>
                        <parameters>true</parameters>

                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.openjdk.jmh</groupId>
                                <artifactId>jmh-generator-annprocess</artifactId>
                                <version>${dep.jmh.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${dep.plugin.jar.version}</version>
                    <configuration>
                        <archive>
                            <addMavenDescriptor>true</addMavenDescriptor>
                            <compress>true</compress>
                            <index>false</index>
                            <manifest>
                                <addClasspath>false</addClasspath>
                                <addDefaultEntries>true</addDefaultEntries>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                                <addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
                                <addBuildEnvironmentEntries>true</addBuildEnvironmentEntries>
                            </manifest>

                            <manifestEntries>
                                <Build-Time>${maven.build.timestamp}</Build-Time>
                                <Project-Java-Version>${javaVersion}</Project-Java-Version>

                                <Creation-Java-Vendor>${java.vendor}</Creation-Java-Vendor>
                                <Creation-Java-Version>${java.version}</Creation-Java-Version>
                                <Creation-Java-Runtime-Name>${java.runtime.name}</Creation-Java-Runtime-Name>
                                <Creation-Java-Runtime-Version>${java.runtime.version}</Creation-Java-Runtime-Version>

                                <Creation-Os-Name>${os.name}</Creation-Os-Name>
                                <Creation-Os-Arch>${os.arch}</Creation-Os-Arch>
                                <Creation-Os-Version>${os.version}</Creation-Os-Version>
                                <Creation-User>${developer1Id} (${developer1Name}), ${developer2Id} (${developer2Name})</Creation-User>
                                <Creation-Time>${maven.build.timestamp}</Creation-Time>

                                <Project-Description>${project.description}</Project-Description>
                                <Project-Url>${project.url}</Project-Url>
                                <Project-Inception-Year>${project.inceptionYear}</Project-Inception-Year>

                                <Organization-Name>${project.organization.name}</Organization-Name>
                                <Organization-Url>${project.organization.url}</Organization-Url>
                            </manifestEntries>
                        </archive>
                        <excludes>
                            <exclude>run-benchmarks.*</exclude>
                        </excludes>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>${dep.plugin.checkstyle.version}</version>
                    <configuration>
                        <failOnViolation>true</failOnViolation>
                        <configLocation>${check.checkstyle.ruleset}</configLocation>
                        <excludes>
                            **/jmh_generated/**/*.java
                        </excludes>
                        <consoleOutput>true</consoleOutput>
                        <includeTestSourceDirectory>true</includeTestSourceDirectory>
                        <logViolationsToConsole>true</logViolationsToConsole>
                        <violationSeverity>warning</violationSeverity>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>${dep.checkstyle.version}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>checkstyle-check</id>
                            <goals>
                                <goal>check</goal>
                            </goals>
                            <phase>test-compile</phase>
                            <!-- fail before lengthy test execution -->
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${dep.plugin.enforcer.version}</version>
                    <configuration>
                        <rules>

                            <requireMavenVersion>
                                <version>[3.9.0,)</version>
                            </requireMavenVersion>
                            <requireJavaVersion>
                                <version>[${javaVersion},)</version>
                            </requireJavaVersion>

                            <requirePluginVersions>
                                <message>Best practice is to always define Maven plugin versions</message>
                                <banTimestamps>false</banTimestamps>

                                <unCheckedPluginList>
                                    org.apache.maven.plugins:maven-clean-plugin,
                                    org.apache.maven.plugins:maven-dependency-plugin,
                                    org.apache.maven.plugins:maven-deploy-plugin,
                                    org.apache.maven.plugins:maven-install-plugin,
                                    org.apache.maven.plugins:maven-resources-plugin,
                                    org.apache.maven.plugins:maven-site-plugin,
                                    org.apache.maven.plugins:maven-surefire-plugin
                                </unCheckedPluginList>
                            </requirePluginVersions>
                        </rules>
                    </configuration>
                    <executions>
                        <execution>
                            <id>default-enforce</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <phase>validate</phase>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>versions-maven-plugin</artifactId>
                    <version>${dep.plugin.versions.version}</version>
                    <configuration>
                        <allowSnapshots>true</allowSnapshots>
                        <ruleSet>
                            <ignoreVersions>
                                <ignoreVersion>
                                    <type>regex</type>
                                    <version>.*(?i)(alpha|beta|rc|cr|preview|milestone|[mb][0-9]+).*</version>
                                </ignoreVersion>
                            </ignoreVersions>
                        </ruleSet>
                    </configuration>
                </plugin>

            </plugins>

        </pluginManagement>

        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${dep.plugin.resources.version}</version>
                <executions>
                    <execution>
                        <id>copy-bench-scripts</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/resources</directory>
                                    <filtering>true</filtering>
                                    <includes>
                                        <include>run-benchmarks.*</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${dep.plugin.shade.version}</version>

                <configuration>
                    <finalName>${project.artifactId}</finalName>
                    <outputFile>${project.build.directory}/${project.artifactId}.jar</outputFile>
                    <shadedArtifactAttached>false</shadedArtifactAttached>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <transformers>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <mainClass>${jmhMainClass}</mainClass>
                        </transformer>
                    </transformers>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>module-info.class</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/LICENSE*</exclude>
                                <exclude>META-INF/MANIFEST.MF</exclude>
                                <exclude>META-INF/NOTICE*</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>

                <executions>
                    <execution>
                        <id>jmh-shade-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${dep.plugin.antrun}</version>
                <executions>
                    <execution>
                        <id>make-scripts-executable</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <chmod file="${project.build.directory}/run-benchmarks.sh" perm="755"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>

    </build>

</project>
